import express from "express";
import cors from "cors";
import bodyParser from "body-parser";
import connectDB from "./src/configs/db.config";
import userRoute from "./src/routes/user.route.js";
import activityRoute from "./src/routes/activity.route.js";
import dotenv from "dotenv";
dotenv.config();
const port = process.env.PORT || 5000;
const app = express();
connectDB(process.env.MONGODB_URI);
// app.use(cors());
// app.use(express.json());
app.use(bodyParser.json());
const urlencodedParser = bodyParser.urlencoded({ extended: true });
app.use('/api/users',userRoute);
app.use('/api/activities',activityRoute);
app.listen(port, () => {
  console.log("Backend is listening on port ", port);
});
